# Generated by Django 2.2.24 on 2021-08-21 23:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('institution', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_num', models.IntegerField()),
                ('proposal', models.URLField()),
                ('granted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField()),
                ('collaborators', models.ManyToManyField(related_name='proposals', to='xc.Person')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xc.Person')),
            ],
        ),
    ]
