# Generated by Django 2.2.24 on 2021-08-21 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='granted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
