# Generated by Django 2.2.24 on 2021-08-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xc', '0004_auto_20210821_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField()),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='project',
        ),
        migrations.AddField(
            model_name='proposal',
            name='project',
            field=models.ManyToManyField(to='xc.Project'),
        ),
    ]
