# Generated by Django 2.2.24 on 2021-08-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xc', '0005_auto_20210822_1635'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name')},
        ),
    ]
