# Generated by Django 2.2.24 on 2021-08-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xc', '0006_auto_20210822_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
