# Generated by Django 2.2.24 on 2021-08-24 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xc', '0007_auto_20210822_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('proposal', models.URLField(blank=True, null=True)),
                ('granted_date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.CharField(blank=True, max_length=400, null=True)),
                ('access', models.CharField(blank=True, max_length=400, null=True)),
                ('active', models.BooleanField()),
                ('collaborators', models.ManyToManyField(related_name='proposals2', to='xc.Person')),
                ('project', models.ManyToManyField(related_name='proposals2', to='xc.Project')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xc.Person')),
            ],
        ),
    ]
